// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Counter struct {
	UserID string
	Count  int64
}

type Credential struct {
	ID              []byte
	PublicKey       []byte
	AttestationType string
	Transport       []byte
	Flags           []byte
	Authenticator   []byte
	UserID          []byte
}

type Dataentry struct {
	ID          int64
	DatapointID int64
	Type        string
	TextValue   sql.NullString
	IntValue    sql.NullInt64
	CreatedAt   time.Time
}

type Datapoint struct {
	ID        int64
	UserID    []byte
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID          []byte
	Name        string
	DisplayName string
}
