// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const createCounter = `-- name: CreateCounter :exec
INSERT INTO counters (user_id, count) VALUES (?, 1)
`

func (q *Queries) CreateCounter(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, createCounter, userID)
	return err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (id, public_key, attestation_type, transport, flags, authenticator, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCredentialParams struct {
	ID              []byte
	PublicKey       []byte
	AttestationType string
	Transport       []byte
	Flags           []byte
	Authenticator   []byte
	UserID          []byte
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createCredential,
		arg.ID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transport,
		arg.Flags,
		arg.Authenticator,
		arg.UserID,
	)
	return err
}

const createDataentry = `-- name: CreateDataentry :one
INSERT INTO dataentries (datapoint_id, type, text_value, int_value) VALUES (?, ?, ?, ?) RETURNING id, datapoint_id, type, text_value, int_value, created_at
`

type CreateDataentryParams struct {
	DatapointID int64
	Type        string
	TextValue   sql.NullString
	IntValue    sql.NullInt64
}

func (q *Queries) CreateDataentry(ctx context.Context, arg CreateDataentryParams) (Dataentry, error) {
	row := q.db.QueryRowContext(ctx, createDataentry,
		arg.DatapointID,
		arg.Type,
		arg.TextValue,
		arg.IntValue,
	)
	var i Dataentry
	err := row.Scan(
		&i.ID,
		&i.DatapointID,
		&i.Type,
		&i.TextValue,
		&i.IntValue,
		&i.CreatedAt,
	)
	return i, err
}

const createDatapoint = `-- name: CreateDatapoint :one
INSERT INTO datapoints (user_id, name) VALUES (?, ?) RETURNING id, user_id, name, created_at
`

type CreateDatapointParams struct {
	UserID []byte
	Name   string
}

func (q *Queries) CreateDatapoint(ctx context.Context, arg CreateDatapointParams) (Datapoint, error) {
	row := q.db.QueryRowContext(ctx, createDatapoint, arg.UserID, arg.Name)
	var i Datapoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, display_name) VALUES (?, ?, ?) RETURNING id, name, display_name
`

type CreateUserParams struct {
	ID          []byte
	Name        string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Name, arg.DisplayName)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.DisplayName)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE id = ? AND user_id = ?
`

type DeleteCredentialParams struct {
	ID     []byte
	UserID []byte
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, arg.ID, arg.UserID)
	return err
}

const deleteDataentry = `-- name: DeleteDataentry :exec
DELETE FROM dataentries WHERE id = ?
`

func (q *Queries) DeleteDataentry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDataentry, id)
	return err
}

const deleteDatapoint = `-- name: DeleteDatapoint :exec
DELETE FROM datapoints WHERE id = ?
`

func (q *Queries) DeleteDatapoint(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDatapoint, id)
	return err
}

const getCounter = `-- name: GetCounter :one
SELECT user_id, count FROM counters WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetCounter(ctx context.Context, userID string) (Counter, error) {
	row := q.db.QueryRowContext(ctx, getCounter, userID)
	var i Counter
	err := row.Scan(&i.UserID, &i.Count)
	return i, err
}

const getCredentialsByUser = `-- name: GetCredentialsByUser :many
SELECT id, public_key, attestation_type, transport, flags, authenticator, user_id FROM credentials WHERE user_id = ?
`

func (q *Queries) GetCredentialsByUser(ctx context.Context, userID []byte) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transport,
			&i.Flags,
			&i.Authenticator,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataentry = `-- name: GetDataentry :one

SELECT id, datapoint_id, type, text_value, int_value, created_at FROM dataentries WHERE id = ? LIMIT 1
`

// Dataentries
func (q *Queries) GetDataentry(ctx context.Context, id int64) (Dataentry, error) {
	row := q.db.QueryRowContext(ctx, getDataentry, id)
	var i Dataentry
	err := row.Scan(
		&i.ID,
		&i.DatapointID,
		&i.Type,
		&i.TextValue,
		&i.IntValue,
		&i.CreatedAt,
	)
	return i, err
}

const getDatapoint = `-- name: GetDatapoint :one

SELECT id, user_id, name, created_at FROM datapoints WHERE id = ? LIMIT 1
`

// Datapoints
func (q *Queries) GetDatapoint(ctx context.Context, id int64) (Datapoint, error) {
	row := q.db.QueryRowContext(ctx, getDatapoint, id)
	var i Datapoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, name, display_name FROM users WHERE id = ? LIMIT 1
`

// Self-Hosted users
func (q *Queries) GetUser(ctx context.Context, id []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.DisplayName)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, display_name FROM users WHERE name = ? LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.DisplayName)
	return i, err
}

const incrementCounter = `-- name: IncrementCounter :one
UPDATE counters SET count = count + 1 WHERE user_id = ? RETURNING count
`

func (q *Queries) IncrementCounter(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementCounter, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDataentriesByDatapoint = `-- name: ListDataentriesByDatapoint :many
SELECT id, datapoint_id, type, text_value, int_value, created_at FROM dataentries WHERE datapoint_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDataentriesByDatapoint(ctx context.Context, datapointID int64) ([]Dataentry, error) {
	rows, err := q.db.QueryContext(ctx, listDataentriesByDatapoint, datapointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dataentry
	for rows.Next() {
		var i Dataentry
		if err := rows.Scan(
			&i.ID,
			&i.DatapointID,
			&i.Type,
			&i.TextValue,
			&i.IntValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatapointsByUser = `-- name: ListDatapointsByUser :many
SELECT id, user_id, name, created_at FROM datapoints WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDatapointsByUser(ctx context.Context, userID []byte) ([]Datapoint, error) {
	rows, err := q.db.QueryContext(ctx, listDatapointsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datapoint
	for rows.Next() {
		var i Datapoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials
SET public_key = ?,
attestation_type = ?,
transport = ?,
flags = ?,
authenticator = ?
WHERE id = ?6
`

type UpdateCredentialParams struct {
	PublicKey       []byte
	AttestationType string
	Transport       []byte
	Flags           []byte
	Authenticator   []byte
	ByID            []byte
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateCredential,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transport,
		arg.Flags,
		arg.Authenticator,
		arg.ByID,
	)
	return err
}

const updateDataentry = `-- name: UpdateDataentry :one
UPDATE dataentries SET type = ?, text_value = ?, int_value = ? WHERE id = ? RETURNING id, datapoint_id, type, text_value, int_value, created_at
`

type UpdateDataentryParams struct {
	Type      string
	TextValue sql.NullString
	IntValue  sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateDataentry(ctx context.Context, arg UpdateDataentryParams) (Dataentry, error) {
	row := q.db.QueryRowContext(ctx, updateDataentry,
		arg.Type,
		arg.TextValue,
		arg.IntValue,
		arg.ID,
	)
	var i Dataentry
	err := row.Scan(
		&i.ID,
		&i.DatapointID,
		&i.Type,
		&i.TextValue,
		&i.IntValue,
		&i.CreatedAt,
	)
	return i, err
}

const updateDatapointName = `-- name: UpdateDatapointName :one
UPDATE datapoints SET name = ? WHERE id = ? RETURNING id, user_id, name, created_at
`

type UpdateDatapointNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateDatapointName(ctx context.Context, arg UpdateDatapointNameParams) (Datapoint, error) {
	row := q.db.QueryRowContext(ctx, updateDatapointName, arg.Name, arg.ID)
	var i Datapoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
